In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1,2,3],[4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7,8,9],[10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [4]:
tensor1.requires_grad

False

In [5]:
tensor2.requires_grad

False

In [6]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [7]:
print(tensor1.grad)

None


In [8]:
print(tensor1.grad_fn)

None


In [9]:
output_tensor = tensor1 + tensor2

In [10]:
output_tensor.requires_grad

True

In [11]:
print(output_tensor.grad)

None


/var/folders/ws/8p7ftd2x7vj_bdhgzwfb6ypr0000gq/T/ipykernel_13443/1906321212.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(output_tensor.grad)


In [12]:
print(output_tensor.grad_fn)

In [13]:
print(tensor1.grad_fn)

None


In [14]:
print(tensor2.grad_fn)

None


In [16]:
output_tensor = (tensor1 + tensor2).mean()
print(output_tensor.grad_fn)

In [17]:
print(tensor1.grad)

None


In [18]:
output_tensor.backward()

In [19]:
print(tensor1.grad)

tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])


In [21]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [22]:
print(tensor2.grad)

None


In [23]:
print(output_tensor.grad)

None


/var/folders/ws/8p7ftd2x7vj_bdhgzwfb6ypr0000gq/T/ipykernel_13443/1906321212.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(output_tensor.grad)


In [25]:
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [26]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [28]:
with torch.no_grad():
    new_tensor = tensor1 * 3
    print('new_tensor = ', new_tensor)
    print('requires_grad for tensor = ', tensor1.requires_grad)
    print('requires_grad for tensor = ', tensor2.requires_grad)
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor =  True
requires_grad for tensor =  False
requires_grad for new_tensor =  False


In [29]:
def calculate(t):
    return t * 2

In [31]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [32]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [33]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [34]:
result_tensor_no_grad.requires_grad

False

In [35]:
with torch.no_grad():
    new_tensor_no_grad = tensor1 * 3
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    with torch.enable_grad():
        new_tensor_grad = tensor1 * 3
        print('new_tensor_grad = ', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [37]:
tensor_one = torch.tensor([[1.0,2.0],[3.0,4.0]], requires_grad = True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [38]:
tensor_two = torch.Tensor([[5,6],[7,8]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [39]:
tensor_one.requires_grad

True

In [41]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [44]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)