In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.rand(4,3)
tensor

tensor([[0.3222, 0.5244, 0.1283],
        [0.3771, 0.1207, 0.2378],
        [0.2473, 0.3034, 0.5422],
        [0.4163, 0.2912, 0.8560]])

In [3]:
type(tensor)

torch.Tensor

In [4]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.32218456, 0.5243621 , 0.12834752],
       [0.3770942 , 0.12065512, 0.23778003],
       [0.24726671, 0.30340338, 0.5422006 ],
       [0.41628194, 0.29121125, 0.85599154]], dtype=float32)

In [5]:
type(numpy_from_tensor)

numpy.ndarray

In [6]:
torch.is_tensor(tensor)

True

In [7]:
torch.is_tensor(numpy_from_tensor)

False

In [9]:
numpy_arr = np.array([[1.0,2.0,3.0],[10.0,20.0,30.0],[100.0,200.0,300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [10]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [11]:
torch.is_tensor(tensor_from_numpy)

True

In [14]:
torch.cuda.is_available()

False

In [15]:
torch.cuda.current_device()

AssertionError: Torch not compiled with CUDA enabled