In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
W = tf.Variable(6, name = 'var_W')
x = tf.constant([10,10], name = 'x')
b = tf.Variable(3, name = 'constant_b')

In [5]:
W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [6]:
x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [8]:
y = W*x + b
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([63, 63], dtype=int32)>

In [9]:
print(y)

tf.Tensor([63 63], shape=(2,), dtype=int32)


In [10]:
print(W*x)

tf.Tensor([60 60], shape=(2,), dtype=int32)


In [11]:
np_result = np.multiply(W, x)
np_result

array([60, 60], dtype=int32)

In [13]:
W.numpy()

6

In [14]:
y.numpy()

array([63, 63], dtype=int32)